# frozen_string_literal: true

require 'pathname'

require_relative '../../result'
require_relative '../../config/api'
require_relative '../../storage/api'
require_relative '../../validation/internal/front_matter_parser'

module Owl
  module Publish
    module Internal
      # (Re)generates a deterministic, idempotent `docs/README.md` index of
      # published task docs. It scans every `docs/TASK-*/` directory (not just
      # the current task), so it is resilient to manual edits/deletions, and it
      # contains NO timestamps — re-running over the same doc set yields a
      # byte-identical file.
      #
      # The generated index is reproducible from `docs/`, so it is rewritten in
      # place WITHOUT a `.bak` sibling (unlike Publisher's artifact copies).
      module DocsIndex
        INDEX_NAME = 'README.md'
        TASK_DIR = /\ATASK-[0-9A-Za-z_-]+\z/
        HEADER = <<~MD
          # Published docs

          Generated by `owl publish` (the `merge_docs` step). Lists task
          artifacts published under `docs/`. Do not edit by hand — re-running
          `owl publish` regenerates this file.
        MD

        module_function

        # Returns Result.ok(updated: bool, path: "docs/README.md"). On dry-run
        # nothing is written (updated: false).
        def regenerate(root:, dry_run:)
          docs_root = resolve_docs_root(root: root)
          return docs_root if docs_root.is_a?(Owl::Result::Err)

          rel_path = relative_index_path(root: root, docs_root: docs_root)
          return Result.ok(updated: false, path: rel_path) if dry_run

          contents = render(docs_root: docs_root)
          Owl::Storage::Api.write(path: docs_root + INDEX_NAME, contents: contents)
          Result.ok(updated: true, path: rel_path)
        end

        def resolve_docs_root(root:)
          config = Owl::Config::Api.load(root: root)
          return config if config.err?

          base = Owl::Storage::Api.resolve(role: 'docs', profile: config.value.active_profile, root: root)
          return base if base.err?

          Pathname.new(base.value.to_s)
        end

        def relative_index_path(root:, docs_root:)
          (docs_root + INDEX_NAME).relative_path_from(Pathname.new(root.to_s)).to_s
        rescue ArgumentError
          (docs_root + INDEX_NAME).to_s
        end

        def render(docs_root:)
          entries = collect_entries(docs_root: docs_root)
          body =
            if entries.empty?
              "_No published docs yet._\n"
            else
              "#{entries.map { |e| render_entry(e) }.join("\n")}\n"
            end
          "#{HEADER}\n#{body}"
        end

        def collect_entries(docs_root:)
          entries = task_dirs(docs_root: docs_root).flat_map do |dir|
            doc_files(dir).map do |file|
              { link: "#{dir.basename}/#{file.basename}", summary: summary_for(file) }
            end
          end
          entries.sort_by { |entry| entry[:link] }
        end

        def task_dirs(docs_root:)
          children = Owl::Storage::Api.children(path: docs_root)
          return [] if children.err?

          children.value.select { |child| child.directory? && child.basename.to_s.match?(TASK_DIR) }
        end

        def doc_files(dir)
          children = Owl::Storage::Api.children(path: dir)
          return [] if children.err?

          files = children.value.select { |child| child.file? && child.extname == '.md' }
          files.sort_by { |child| child.basename.to_s }
        end

        def summary_for(file)
          read = Owl::Storage::Api.read(path: file)
          return nil if read.err?

          parsed = Owl::Validation::Internal::FrontMatterParser.parse(read.value)
          summary = parsed[:front_matter].is_a?(Hash) ? parsed[:front_matter]['summary'] : nil
          return nil unless summary.is_a?(String) && !summary.strip.empty?

          summary.gsub(/\s+/, ' ').strip
        end

        def render_entry(entry)
          line = "- [#{entry[:link]}](#{entry[:link]})"
          entry[:summary] ? "#{line} — #{entry[:summary]}" : line
        end
      end
    end
  end
end
